https://download.kiwix.org/zim/ted/ted_en_playlist-understanding-world-economics_2021-12.zim
https://download.kiwix.org/zim/zimit/www.ready.gov_en_2024-06.zim
https://download.kiwix.org/zim/ted/ted_en_global_issues_2023-09.zim
https://download.kiwix.org/zim/ted/ted_en_playlist-little-known-big-history_2021-12.zim
https://download.kiwix.org/zim/videos/aimhi_en_science-website_2022-01.zimhttps://download.kiwix.org/zim/ted/ted_en_science_2023-08.zim
https://download.kiwix.org/zim/ted/ted_en_technology_2023-09.zim
https://download.kiwix.org/zim/ted/ted_en_design_2023-09.zim
https://download.kiwix.org/zim/wikipedia/wikipedia_en_computer_maxi_2024-06.zim
https://download.kiwix.org/zim/zimit/opendatastructures.org_en_all_2024-06.zim
https://download.kiwix.org/zim/ted/ted_en_playlist-a-day-trip-to-antarctica_2022-08.zim
https://download.kiwix.org/zim/ted/ted_en_playlist-did-you-know_2021-12.zim
https://download.kiwix.org/zim/ted/ted_en_playlist-how-to-be-your-own-advocate_2021-12.zim
https://download.kiwix.org/zim/ted/ted_mul_asteroid_2024-06.zim
https://download.kiwix.org/zim/ted/ted_en_playlist-don-t-you-wish-you-lived-here_2022-08.zim
https://download.kiwix.org/zim/ted/ted_en_playlist-what-makes-businesses-work_2021-12.zim
https://download.kiwix.org/zim/ted/ted_en_playlist-history-visualized_2021-01.zim
https://download.kiwix.org/zim/ifixit/ifixit_en_all_2024-03.zim
https://download.kiwix.org/zim/ted/ted_en_playlist-unheard-and-forgotten-stories_2021-01.zim
https://download.kiwix.org/zim/ted/ted_mul_bees_2024-06.zim
https://download.kiwix.org/zim/ted/ted_mul_biosphere_2024-06.zim
https://download.kiwix.org/zim/ted/ted_mul_antarctica_2024-06.zim
https://download.kiwix.org/zim/ted/ted_en_playlist-moocs-101_2021-12.zim
https://download.kiwix.org/zim/ted/ted_mul_3d-printing_2024-06.zim
https://download.kiwix.org/zim/ted/ted_en_playlist-fascinating-history_2022-08.zim
https://download.kiwix.org/zim/ted/ted_en_playlist-sharks_2022-08.zim
https://download.kiwix.org/zim/ted/ted_en_playlist-sounds-of-the-wild_2022-08.zim
https://download.kiwix.org/zim/ted/ted_en_playlist-talks-on-water_2021-01.zim
https://download.kiwix.org/zim/ted/ted_en_playlist-the-global-power-shift_2021-12.zim
https://download.kiwix.org/zim/stack_exchange/raspberrypi.stackexchange.com_en_all_2024-05.zim
https://download.kiwix.org/zim/ted/ted_mul_aids_2024-06.zim
https://download.kiwix.org/zim/ted/ted_en_playlist-emerging-markets_2021-12.zim
https://download.kiwix.org/zim/ted/ted_en_playlist-curator-s-picks-top-10-ted-talks-of-2018_2022-08.zim
https://download.kiwix.org/zim/ted/ted_en_playlist-live-out-your-sci-fi-dreams_2021-01.zim
https://download.kiwix.org/zim/ted/ted_en_playlist-stand-up-to-bullying_2021-12.zim
https://download.kiwix.org/zim/ted/ted_en_playlist-the-fight-against-viruses_2021-12.zim
https://download.kiwix.org/zim/ted/ted_mul_ancient-world_2024-06.zim
https://download.kiwix.org/zim/videos/oer4schools_en_all_2024-03.zim
https://download.kiwix.org/zim/ted/ted_mul_architecture_2024-06.zim
https://download.kiwix.org/zim/ted/ted_en_playlist-why-we-need-bees_2022-08.zim
https://download.kiwix.org/zim/ted/ted_en_playlist-talks-on-artificial-intelligen_2021-12.zim
https://download.kiwix.org/zim/ted/ted_en_playlist-technology-designed-by-nature_2021-12.zim
https://download.kiwix.org/zim/ted/ted_en_playlist-what-is-consciousness_2021-12.zim
https://download.kiwix.org/zim/videos/voa_learning_english-news-literacy_2023-11.zim
https://download.kiwix.org/zim/ted/ted_en_playlist-planes-trains-and-automobiles_2021-01.zim
https://download.kiwix.org/zim/videos/voa_learning_english-everyday-grammar-tv_2023-11.zim
https://download.kiwix.org/zim/videos/voa_learning_english-how-to-pronounce_2023-11.zim
https://download.kiwix.org/zim/videos/voa_learning_english-let-s-learn-english_2023-11.zim
https://download.kiwix.org/zim/videos/voa_learning_english-let-s-teach-english_2023-11.zim
https://download.kiwix.org/zim/ted/ted_mul_africa_2024-06.zim
https://download.kiwix.org/zim/ted/ted_en_playlist-reduce-reuse-recycle_2021-12.zim
https://download.kiwix.org/zim/videos/voa_learning_english-word-of-the-day_2023-11.zim
https://download.kiwix.org/zim/ted/ted_en_playlist-the-air-around-us_2022-08.zim
https://download.kiwix.org/zim/videos/voa_learning_english-let-s-learn-english-level-2_2023-11.zim
https://download.kiwix.org/zim/videos/voa_learning_english-eim-english-in-a-minute_2023-11.zim
https://download.kiwix.org/zim/ted/ted_en_playlist-internet-origin-stories_2021-12.zim
https://download.kiwix.org/zim/ted/ted_en_playlist-how-leaders-inspire_2023-04.zim
https://download.kiwix.org/zim/ted/ted_en_playlist-what-makes-earth-so-special_2021-12.zim
https://download.kiwix.org/zim/ted/ted_en_playlist-goals_2021-01.zim
https://download.kiwix.org/zim/ted/ted_en_playlist-the-end-of-oil_2021-12.zim
https://download.kiwix.org/zim/ted/ted_en_playlist-are-we-alone-in-the-universe_2022-08.zim
https://download.kiwix.org/zim/ted/ted_en_playlist-the-10-most-popular-tedx-talks_2021-01.zim
https://download.kiwix.org/zim/ted/ted_en_playlist-how-to-overcome-your-fears_2021-01.zim
https://download.kiwix.org/zim/ted/ted_en_playlist-the-world-of-tiny-things_2021-01.zim
https://download.kiwix.org/zim/ted/teded_en_all_2024-04.zim
https://download.kiwix.org/zim/other/khanacademy_en_all_2023-03.zim
https://download.kiwix.org/zim/wikihow/wikihow_en_maxi_2023-03.zim